esphome:
  name: esphome-web-ccc028
  friendly_name: ESP Helligkeit
  name_add_mac_suffix: false

esp32:
  variant: esp32
  framework:
    type: esp-idf

logger:

api:

ota:
  platform: esphome

# WLAN
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

esp32_ble_tracker:

sensor:
  - platform: bh1750
    name: "Helligkeit"
    address: 0x23
    update_interval: 30s

  # Xiaomi Mi Scale (nur falls ESP32 BLE aktiv)
  - platform: xiaomi_miscale
    mac_address: "70:87:9e:6e:ba:61"
    weight:
      name: "Xiaomi Mi Scale Gewicht"
      accuracy_decimals: 2
      unit_of_measurement: "kg"
      icon: "mdi:scale-bathroom"
    
# MQTT Konfiguration
mqtt:
  broker: !secret mqtt_broker
  port: 1884
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false
  topic_prefix: Helligkeit_Flur
  id: mqtt_client
